cmp/accounts/urls.py
from django.urls import path
from accounts import views
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path('', views.indexView, name='index'),
    path('profile_settings/', views.accountSettings, name='profile_settings'),
    path('signup/', views.registerPage, name='signup'),
    path('user/', views.UserView.as_view(), name='user'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name="logout"),
    path('customers/<str:pk>/', views.CustomerView.as_view(), name='customers'),
    path('products/', views.ProductView.as_view(), name='products'),
    path('createorder/<str:pk>/', views.createOrder, name='createorder'),
    path('updateorder/<str:pk>/', views.OrderUpdateView.as_view(), name='updateorder'),
    path('deleteorder/<str:pk>/', views.OrderDeleteView.as_view(), name='deleteorder'),
]

cmp/cmp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',include('accounts.urls')),
    # path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
         name="reset_password"),
         
    path('reset_password_sent/',
            auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"),
            name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name="password_reset_confirm"),

    path('reset_password_complete/',
            auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"),
            name="password_reset_complete"),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cmp/accounts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User,PermissionsMixin
# Create your models here.


# class User(User,PermissionsMixin):
# 	def __str__(self):
# 		return f"@{self.username}"

class Customer(models.Model):
	user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
	name = models.CharField(max_length=200, null=True)
	phone = models.CharField(max_length=200, null=True)
	email = models.CharField(max_length=200, null=True)
	profile_pic = models.ImageField(upload_to='accounts/profile_pics',
					default="accounts/profile_pics/user.png",null=True, blank=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)


	def __str__(self):
		return self.name

class Tag(models.Model):
	name = models.CharField(max_length=200, null=True)

	def __str__(self):
		return self.name


class Product(models.Model):
	CATEGORY = (
			('Indoor', 'Indoor'),
			('Out Door', 'Out Door'),
			)

	name = models.CharField(max_length=200, null=True)
	price = models.FloatField(null=True)
	category = models.CharField(max_length=200, null=True, choices=CATEGORY)
	description = models.CharField(max_length=200, null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	tags = models.ManyToManyField(Tag)

	def __str__(self):
		return self.name

class Order(models.Model):
	STATUS = (
			('Pending', 'Pending'),
			('Out for delivery', 'Out for delivery'),
			('Delivered', 'Delivered'),
			)

	customer = models.ForeignKey(Customer, null=True, on_delete= models.SET_NULL)
	product = models.ForeignKey(Product, null=True, on_delete= models.SET_NULL)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	status = models.CharField(max_length=200, null=True, choices=STATUS)
	note = models.CharField(max_length=1000, null=True)

	def __str__(self):
		return self.product.name

	# def get_absolute_url(self):
	# 	return reverse('accounts:customers', kwargs={'pk':self.pk})

cmp/accounts/forms.py
from django.forms import ModelForm
from .models import Order,Customer
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserCreateForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

class CustomerForm(ModelForm):
	class Meta:
		model = Customer
		fields = '__all__'
		exclude = ['user']

class OrderCreateForm(ModelForm):
	class Meta:
		model = Order
		fields = '__all__'

cmp/accounts/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView
from accounts.models import Product,Customer,Order
from django.urls import reverse_lazy,reverse
from accounts.forms import OrderCreateForm, UserCreateForm,CustomerForm
from django.forms import inlineformset_factory
from accounts.filters import OrderFilter
from django.contrib.auth import authenticate, login, logout
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
# from django.contrib.auth import get_user_model
from accounts.decorators import allowed_users,admin_only,unauthenticated_user
from django.utils.decorators import method_decorator
from django.contrib.auth.models import Group

# Create your views here.

# User = get_user_model()

@unauthenticated_user
def registerPage(request):

	form = UserCreateForm()
	if request.method == 'POST':
		form = UserCreateForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')


			messages.success(request, 'Account was created for ' + username)

			return redirect('accounts:login')


	context = {'form':form}
	return render(request, 'accounts/signup.html', context)

@login_required
@allowed_users(allowed_roles=['customer'])
def accountSettings(request):
	customer = request.user.customer
	form = CustomerForm(instance=customer)

	if request.method == 'POST':
		form = CustomerForm(request.POST, request.FILES,instance=customer)
		if form.is_valid():
			form.save()


	context = {'form':form}
	return render(request, 'accounts/account_settings.html', context)

def loginPage(request):
	if request.user.is_authenticated:
		return redirect('accounts:index')
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect('accounts:index')
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'accounts/login.html', context)

@login_required
def logoutUser(request):
	logout(request)
	return redirect('accounts:login')

# class OrderCreateView(CreateView):
# 	# form_class = OrderCreateForm
# 	model = Order
# 	fields = ('customer','product','status')
# 	success_url = reverse_lazy('accounts:index')
#
# 	# def form_valid(self, form):
# 	# 	form.instance.customer = self.request.user
# 	# 	return super().form_valid(form)
#
# 	# def get_context_data(self, **kwargs):
# 	# 	context = super().get_context_data(**kwargs)
# 	# 	customer = Customer.objects.get(id=kwargs['pk'])
# 	# 	form = OrderCreateForm(initial={'customer':customer})

@login_required
@allowed_users(allowed_roles=['admin'])
def createOrder(request, pk):
	OrderFormSet = inlineformset_factory(Customer, Order, fields=('product', 'status'), extra=5 )
	customer = Customer.objects.get(id=pk)
	formset = OrderFormSet(queryset=Order.objects.none(),instance=customer)
	# form = OrderCreateForm(initial={'customer':customer})
	if request.method == 'POST':
		formset = OrderFormSet(request.POST, instance=customer)
		if formset.is_valid():
			formset.save()
			return redirect('/')

	context = {'form':formset,'customer':customer}
	return render(request, 'accounts/order_form.html', context)

@method_decorator(allowed_users(allowed_roles=['admin']), name='dispatch')
class OrderUpdateView(LoginRequiredMixin,UpdateView):
	model = Order
	fields = ('product','status')
	success_url = reverse_lazy('accounts:index')
	# def get_absolute_url(self):
	# 	return reverse("accounts:customers", kwargs={"pk": self.object.pk})

@method_decorator(allowed_users(allowed_roles=['admin']), name='dispatch')
class OrderDeleteView(LoginRequiredMixin,DeleteView):
	model = Order
	context_object_name = 'order'
	success_url = reverse_lazy('accounts:index')

# @method_decorator(admin_only, name='dispatch')
# class IndexView(LoginRequiredMixin,TemplateView):
# 	template_name = 'accounts/dashboard.html'
#
# 	def get_context_data(self, **kwargs):
# 		context = super().get_context_data(**kwargs)
# 		orders = Order.objects.all()
# 		customers = Customer.objects.all()
#
# 		total_customers = customers.count()
# 		total_orders = orders.count()
# 		delivered = orders.filter(status='Delivered').count()
# 		pending = orders.filter(status='Pending').count()
#
# 		context = {'orders':orders,'customers':customers, 'total_orders':total_orders,'delivered':delivered,
# 				   'pending':pending}
# 		return context


	# def get(self, request, *args, **kwargs):
	# 	return HttpResponse('/accounts/dashboard.html')
	# def dispatch(self, *args, **kwargs):
	# 	return super(IndexView, self).dispatch(*args, **kwargs)
	# def get(self, request, *args, **kwargs):
	# 	return render(request, 'accounts/dashboard.html',context_instance=RequestContext(request))

@login_required
@admin_only
def indexView(request):
	orders = Order.objects.all()
	customers = Customer.objects.all()

	total_customers = customers.count()

	total_orders = orders.count()
	delivered = orders.filter(status='Delivered').count()
	pending = orders.filter(status='Pending').count()

	context = {'orders':orders, 'customers':customers,
	'total_orders':total_orders,'delivered':delivered,
	'pending':pending }

	return render(request, 'accounts/dashboard.html', context)

@method_decorator(allowed_users(allowed_roles=['admin']), name='dispatch')
class CustomerView(LoginRequiredMixin,TemplateView):
	template_name = 'accounts/customers.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		customer = Customer.objects.get(id=kwargs['pk'])
		# Relation between order and customer table
		orders = customer.order_set.all()
		order_count = orders.count()

		myFilter = OrderFilter(self.request.GET, queryset=orders)
		orders = myFilter.qs

		context = {'customer':customer, 'orders':orders, 'order_count':order_count,'myFilter':myFilter}
		return context


@method_decorator(allowed_users(allowed_roles=['admin']), name='dispatch')
class ProductView(LoginRequiredMixin,TemplateView):
	template_name = 'accounts/products.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		products = Product.objects.all()
		context = {'products':products}
		return context


# Function Based View
# def products(request):
# 	products = Product.objects.all()
#
# 	return render(request, 'accounts/products.html', {'products':products})

@method_decorator(allowed_users(allowed_roles=['customer']), name='dispatch')
class UserView(LoginRequiredMixin,TemplateView):
	template_name = 'accounts/user.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		orders = self.request.user.customer.order_set.all()

		total_orders = orders.count()
		delivered = orders.filter(status='Delivered').count()
		pending = orders.filter(status='Pending').count()

		context = {'orders':orders, 'total_orders':total_orders,'delivered':delivered,'pending':pending}
		return context

cmp/accounts/templates/accounts/account_settings.html
{%  extends 'accounts/base.html' %}
{% load static %}
{% block bodyblock %}

<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>

<br>
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<a class="btn btn-warning" href="{% url 'accounts:index' %}"> &#8592; Back to Profile</a>
			<hr>
			<h3 style="text-align: center">Account Settings</h3>
			<hr>
			{% if request.user.customer.profile_pic %}
    		<img class="profile-pic" src="{{request.user.customer.profile_pic.url}}" >
			{% endif %}


		</div>
	</div>
	<div class="col-md-9">
		<div class="card card-body">

			<form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}

			<input class="btn btn-primary" type="submit" name="Update Information">
			</form>
		</div>
	</div>
</div>



{% endblock %}

cmp/accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>CRM</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/main.css' %}">
  </head>
  <body>
    {% include 'accounts/navbar.html' %}
    {% block bodyblock %}
    {% endblock %}

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

cmp/accounts/templates/accounts/customers.html
{% extends "accounts/base.html" %}
{% block bodyblock %}
<br>
<div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h5>Customer: {{customer.name}}</h5>
        <hr>
        <a class="btn btn-outline-info  btn-sm btn-block" href="">Update Customer</a>
        <a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'accounts:createorder' pk=customer.id %}">Place Order</a>

      </div>
    </div>

    <div class="col-md">
      <div class="card card-body">
        <h5>Contact Information</h5>
        <hr>
        <p>Email: {{customer.email}}</p>
			  <p>Phone: {{customer.phone}}</p>
      </div>
    </div>

    <div class="col-md">
      <div class="card card-body">
        <h5>Total Orders</h5>
        <hr>
        <h1 style="text-align: center;padding: 10px">{{order_count}}</h1>
      </div>
    </div>
</div>


<br>
<div class="row">
    <div class="col">
      <div class="card card-body">
        <form method="get">
				      {{myFilter.form}}
          <button class="btn btn-primary" type="submit">Search</button>
        </form>
      </div>
    </div>

</div>
<br>

<div class="row">
    <div class="col-md">
      <div class="card card-body">
        <table class="table table-sm">
          <tr>
            <th>Product</th>
            <th>Note</th>
            <th>Category</th>
            <th>Date Orderd</th>
            <th>Status</th>
            <th>Update</th>
            <th>Remove</th>
          </tr>
        {% for order in orders %}

  				<tr>
  					<td>{{order.product}}</td>
            <td>{{order.note}}</td>
  					<td>{{order.product.category}}</td>
  					<td>{{order.date_created}}</td>
  					<td>{{order.status}}</td>
            <td><a class="btn btn-sm btn-info" href="{% url 'accounts:updateorder' pk=order.id %}">Update</a></td>
						<td><a class="btn btn-sm btn-danger" href="{% url 'accounts:deleteorder' pk=order.id %}">Delete</a></td>
  				</tr>
				{% endfor %}

        </table>
      </div>
    </div>
</div>
{% endblock %}

cmp/accounts/templates/accounts/dashboard.html
{% extends "accounts/base.html" %}
{% block bodyblock %}
{%  include 'accounts/status.html' %}
<br>
<div class="row">
<div class="col-md-5">
  <h5>CUSTOMERS:</h5>
  <hr>
  <div class="card card-body">
    <a class="btn btn-primary  btn-sm btn-block" href="">Create Customer</a>
    <table class="table table-sm">
      <tr>
        <th></th>
        <th>Customer</th>
        <th>Phone</th>
      </tr>

      {% for customer in customers %}
					<tr>
            <td><a class="btn btn-sm btn-info" href="{% url 'accounts:customers' pk=customer.id %}">View</a></td>
						<td><a href="{% url 'accounts:customers' pk=customer.id %}">{{customer.name}}</a></td>
						<td>{{customer.phone}}</td>
					</tr>
			{% endfor %}

    </table>
  </div>
</div>

<div class="col-md-7">
  <h5>LAST 5 ORDERS</h5>
  <hr>
  <div class="card card-body">
    <table class="table table-sm">
      <tr>
        <th>Product</th>
        <th>Date Orderd</th>
        <th>Status</th>
        <th>Update</th>
        <th>Remove</th>
      </tr>

      {% for order in orders %}
					<tr>
						<td>{{order.product}}</td>
						<td>{{order.date_created}}</td>
						<td>{{order.status}}</td>
						<td><a class="btn btn-sm btn-info" href="{% url 'accounts:updateorder' pk=order.id %}">Update</a></td>
						<td><a class="btn btn-sm btn-danger" href="{% url 'accounts:deleteorder' pk=order.id %}">Delete</a></td>

					</tr>
			{% endfor %}
    </table>
  </div>
</div>

</div>
{% endblock %}

cmp/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'accounts:signup' %}" class="ml-2">Sign Up</a>
					</div>

					<div class="d-flex justify-content-center links">
						Forgot password? <a href="{% url 'reset_password' %}" class="ml-2">Reset password</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>

</html>

cmp/accounts/templates/accounts/navbar.html
{% load static %}
<style>
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'accounts:index' %}">
    <img src="{% static 'accounts/images/logo.png' %}">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      {% if request.user.is_staff %}
      <a class="nav-item nav-link active" href="{% url 'accounts:index' %}">Home</a>
      <a class="nav-item nav-link" href="{% url 'accounts:products' %}">Products</a>
      <a class="nav-item nav-link" href="#">Customer</a>
      {% else %}
       <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:profile_settings' %}">Settings</a>
      </li>
      {% endif %}
    </div>
  </div>
  <span class="hello-msg">Hello, {{request.user}}</span>
  <span ><a  class="hello-msg" href="{% url 'accounts:logout' %}">Logout</a></span>
</nav>

cmp/accounts/templates/accounts/order_confirm_delete.html
{%  extends 'accounts/base.html' %}
{% load static %}
{% block bodyblock %}

<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">


			<p>Are you sure you want to delete "{{order.product}}"?</p>

			<form action="{% url 'accounts:deleteorder' pk=order.id  %}" method="POST">

				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'accounts:index' %}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="Confirm">
			</form>
		</div>
	</div>
</div>

{% endblock %}

cmp/accounts/templates/accounts/order_form.html
{%  extends 'accounts/base.html' %}
{% load static %}
{% block bodyblock %}
<h1>
  Customer Name: {{customer.name}}
</h1>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">

			<form action="" method="POST">
				{% csrf_token %}
        {{ form.management_form }}
        {% for field in form %}
					{{field}}
					<hr>
				{% endfor %}


				<input type="submit" class='btn btn-primary' name="Submit">
			</form>

		</div>
	</div>
</div>


{% endblock %}

cmp/accounts/templates/accounts/password_reset.html
<h3>Password reset</h3>

<p>Forgotten your password? Enter your email address below,
  and we’ll email instructions for setting a new one.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Send email">

</form>

cmp/accounts/templates/accounts/password_reset_confirm.html
<h3>Enter new password</h3>

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form method="post">
	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Update Password">
</form>

cmp/accounts/templates/accounts/password_reset_done.html
<h3>Password reset complete</h3>

<p>Your password has been set. You may go ahead and log in now.</p>

<a href="{% url 'accounts:login' %}">Log in</a>

cmp/accounts/templates/accounts/products.html
{% extends "accounts/base.html" %}
{% block bodyblock %}
<br>

  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h5>Products</h5>
      </div>
      <div class="card card-body">
        <table class="table">
          <tr>
            <th>Product</th>
            <th>Category</th>
            <th>Price</th>
          </tr>

          {% for item in products %}
            <tr>
              <td>{{item.name}}</td>
              <td>{{item.category}}</td>
              <td>{{item.price}}</td>
            </tr>
          {% endfor %}

        </table>
      </div>
    </div>

  </div>

{% endblock %}

cmp/accounts/templates/accounts/status.html
<br>

<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Total Orders</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{total_orders}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Delivered</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{delivered}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Pending</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{pending}}</h3>
			  	</div>
			</div>
		</div>
	</div>
</div>